name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: tungbach12
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake-dark.png?color_snake=green&color_dots=#0e4429,#006d32,#26a641,#39d353

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: output
